test: False

train:
  epochs: 1
  batch_size: 4
  lr: 0.001
  betas: [0.9, 0.999]

model:
  pretrained: "resnet50"
  layer: 1
  individual: False

device: "cuda:0"

data:
  # imgs_path: '/home1/r/rphadnis/idiographic_model/images'
  train_csv_path: '/home1/r/rphadnis/idiographic_model/train_ratings.csv'
  val_csv_path: '/home1/r/rphadnis/idiographic_model/val_ratings.csv'
  test_csv_path: '/home1/r/rphadnis/idiographic_model/test_ratings.csv'
  features_path: '/home1/r/rphadnis/idiographic_model/features.npy'

save: '/home1/r/rphadnis/idiographic_model/results/'
