test: False

train:
  epochs: 1
  batch_size: 4
  lr: 0.001
  betas: [0.9, 0.999]

model:
  pretrained: "resnet50"
  layer: 1
  individual: False

device: "cuda:0"

data:
  imgs_path: '/home1/r/rphadnis/idiographic_model/images'
  csv_path: '/home1/r/rphadnis/idiographic_model/ratings.csv'

save: '/home1/r/rphadnis/idiographic_model/results/'
